[package]
name = "margin-pool"
version = "0.1.0"
description = "Holds all collateral in PDA-owned SPL token accounts"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "margin_pool"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
kamino-lend = "0.4"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
